name: Continuous integration

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          # - arch: x86_64-apple-darwin
          #   os: macos-latest
          #   file: surreal-${{ github.ref_name }}.darwin-amd64
          #   opts: --features storage-tikv
          # - arch: aarch64-apple-darwin
          #   os: macos-latest
          #   file: surreal-${{ github.ref_name }}.darwin-arm64
          #   opts: --features storage-tikv
          # - arch: x86_64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   file: surreal-${{ github.ref_name }}.linux-amd64
          #   opts: --features storage-tikv
          # - arch: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          #   file: surreal-${{ github.ref_name }}.linux-arm64
          #   opts: --features storage-tikv
          - arch: x86_64-pc-windows-msvc
            os: windows-latest
            file: surreal-${{ github.ref_name }}.windows-amd64
            opts:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          repository: 'surrealdb/surrealdb'

      - name: Cache cargo assets
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.arch }}-build-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Prepare environment
        if: contains(matrix.arch, 'windows') && endsWith(matrix.arch, '-gnu')
        run: echo "C:\msys64\usr\bin;$Env:Path" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

      - name: Install dependencies
        if: contains(matrix.arch, 'windows') && endsWith(matrix.arch, '-msvc')
        run: |
          vcpkg integrate install
          vcpkg install openssl:x64-windows-static

      - name: Install dependencies
        if: contains(matrix.arch, 'linux') && endsWith(matrix.arch, '-gnu')
        run: |
          sudo apt-get -y update
          sudo apt-get -y install musl-tools qemu-user libc6-dev-arm64-cross
          sudo apt-get -y install g++-aarch64-linux-gnu gcc-aarch64-linux-gnu

      - name: Install FoundationDB
        if: contains(matrix.arch, 'linux') && startsWith(matrix.arch, 'x86_64')
        run: |
          curl -sLO https://github.com/apple/foundationdb/releases/download/6.3.23/foundationdb-clients_6.3.23-1_amd64.deb
          sudo dpkg -i --force-architecture foundationdb-clients_6.3.23-1_amd64.deb
          rm -rf foundationdb-clients_6.3.23-1_amd64.deb

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: ${{ matrix.arch }}

      - name: Output package versions
        run: go version ; cargo version ; rustc --version ; cmake --version ; gcc --version ; g++ --version ; perl -v

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.opts }} --release --locked --target ${{ matrix.arch }}
        env:
          BINDGEN_EXTRA_CLANG_ARGS_aarch64-unknown-linux-gnu: "-I/usr/aarch64-linux-gnu/include/"
          RUSTFLAGS: "-C target-feature=+crt-static -C link-arg=libvcruntime.lib"

      - name: Package binaries
        if: ${{ !contains(matrix.arch, 'windows') }}
        shell: bash
        run: |
          cd target/${{ matrix.arch }}/release
          chmod +x surreal
          tar -zcvf ${{ matrix.file }}.tgz surreal
          echo $(shasum -a 256 ${{ matrix.file }}.tgz | cut -f1 -d' ') > ${{ matrix.file }}.txt
          cd -

      - name: Package binaries
        if: ${{ contains(matrix.arch, 'windows') }}
        shell: bash
        run: |
          cd target/${{ matrix.arch }}/release
          cp surreal.exe ${{ matrix.file }}.exe
          echo $(shasum -a 256 ${{ matrix.file }}.exe | cut -f1 -d' ') > ${{ matrix.file }}.txt
          cd -

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.file }}
          path: |
            target/${{ matrix.arch }}/release/surreal
            target/${{ matrix.arch }}/release/${{ matrix.file }}.tgz
            target/${{ matrix.arch }}/release/${{ matrix.file }}.txt
            target/${{ matrix.arch }}/release/${{ matrix.file }}.exe
